from django.urls import path
from . import views, v2_views

urlpatterns = [
    path('services/legacy/', v2_views.legacy_service, name='legacy_service'),
    path('services/<uuid:public_id>/', v2_views.service_detail, name='service_detail'),
    path('services/<uuid:public_id>/delivery/', v2_views.service_delivery, name='service_delivery'),
    path('services/<uuid:public_id>/action/', v2_views.service_action, name='service_action'),
    path('nodes/', v2_views.nodes, name='nodes'),
    path('subscriptions/create/', v2_views.subscription_create, name='subscription_create'),
    path('subscriptions/<uuid:public_id>/action/', v2_views.subscription_action, name='subscription_action'),
    path('d/<str:token>/', v2_views.download, name='v2_download'),
    path('d/<str:token>/<slug:resource>/', v2_views.download, name='v2_resource'),
    path('manage/allocations/', v2_views.allocations, name='allocations'),
    path('manage/resources/', v2_views.resources, name='resources'),
    path('manage/capacity/', v2_views.capacities, name='capacities'),
    path('manage/jobs/', v2_views.jobs, name='jobs'),
    path('manage/jobs/<uuid:public_id>/retry/', v2_views.retry_job, name='retry_job'),
    path('', views.dashboard, name='dashboard'), path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'), path('logout/', views.logout_page, name='logout'),
    path('account/', views.account, name='account'), path('guide/', views.guide, name='guide'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('subscriptions/rotate/', views.rotate_subscriptions, name='rotate_subscriptions'),
    path('s/<str:token>/<str:device>', views.download, name='download'),
    path('r/<str:token>/<str:artifact>', views.resource_download, name='resource_download'),
    path('manage/users/', views.users, name='users'),
    path('manage/subscriptions/', views.admin_subscriptions, name='admin_subscriptions'),
    path('manage/users/new/', views.user_create, name='user_create'),
    path('manage/users/<int:pk>/', views.user_edit, name='user_edit'),
    path('manage/invites/', views.invites, name='invites'),
    path('manage/invites/<int:pk>/revoke/', views.revoke_invite, name='revoke_invite'),
    path('manage/operations/', views.operations, name='operations'),
    path('manage/client-routing/', views.client_direct_rules, name='client_direct_rules'),
    path('manage/client-direct/', views.client_direct_rules, name='client_direct_rules_legacy'),
    path('manage/client-direct/export/', views.client_direct_export, name='client_direct_export'),
    path('manage/client-direct/policy/', views.client_direct_policy_export, name='client_direct_policy_export'),
    path('manage/client-routing/proxy.json', views.client_proxy_export, name='client_proxy_export'),
]
