# Generated by Django 5.2.17 on 2026-09-23 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exact', '精确域名'), ('suffix', '域名及子域名'), ('regex', '限定域名正则')], max_length=8)),
                ('value', models.CharField(max_length=253)),
                ('scope_domain', models.CharField(blank=True, max_length=253)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='unique_client_direct_rule')],
            },
        ),
    ]
