# Generated by Django 5.2.17 on 2026-09-30 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_clientrule_outbound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('direct', '服务器出站'), ('upstream', '上游链路')], max_length=24)),
                ('config_ref', models.CharField(blank=True, max_length=120)),
                ('fail_closed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('reality', 'Reality'), ('ws', 'WebSocket'), ('hy2', 'Hysteria 2'), ('anytls', 'AnyTLS')], max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('config_ref', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('adapter', models.CharField(default='unconfigured', max_length=40)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_bytes', models.PositiveBigIntegerField()),
                ('reset_day', models.PositiveSmallIntegerField(default=1)),
                ('service_months', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('requested_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('applied_revision', models.PositiveIntegerField(default=0)),
                ('applied_snapshot', models.JSONField(default=dict)),
                ('state', models.CharField(default='pending', max_length=24)),
                ('usage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('client', models.CharField(choices=[('windows', 'Windows / v2rayN'), ('v2rayng', 'Android / v2rayNG'), ('android', 'Android / SFA')], max_length=16)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('applied_generation', models.PositiveIntegerField(default=0)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='portal.entitlement')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=24)),
                ('revision', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(default='queued', max_length=24)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_id', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=80)),
                ('receipt', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='portal.devicesubscription')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='portal.entitlement')),
            ],
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('used_bytes', models.PositiveBigIntegerField(default=0)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='portal.entitlement')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('egress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='portal.egress')),
                ('ingress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='portal.ingress')),
            ],
        ),
        migrations.AddField(
            model_name='entitlement',
            name='lines',
            field=models.ManyToManyField(related_name='entitlements', to='portal.line'),
        ),
        migrations.AddField(
            model_name='devicesubscription',
            name='lines',
            field=models.ManyToManyField(to='portal.line'),
        ),
        migrations.CreateModel(
            name='NodeIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generation', models.PositiveIntegerField()),
                ('credential_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(default='candidate', max_length=24)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.line')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='portal.devicesubscription')),
            ],
        ),
        migrations.AddField(
            model_name='ingress',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresses', to='portal.server'),
        ),
        migrations.AddField(
            model_name='egress',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresses', to='portal.server'),
        ),
        migrations.CreateModel(
            name='UsageStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.CharField(max_length=80)),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('upload_bytes', models.PositiveBigIntegerField(default=0)),
                ('download_bytes', models.PositiveBigIntegerField(default=0)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='portal.nodeidentity')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField()),
                ('upload_delta', models.PositiveBigIntegerField()),
                ('download_delta', models.PositiveBigIntegerField()),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='portal.billingcycle')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.usagestream')),
            ],
        ),
        migrations.AddConstraint(
            model_name='billingcycle',
            constraint=models.UniqueConstraint(fields=('entitlement', 'starts_at'), name='unique_billing_cycle'),
        ),
        migrations.AddConstraint(
            model_name='billingcycle',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='positive_billing_period'),
        ),
        migrations.AddConstraint(
            model_name='nodeidentity',
            constraint=models.UniqueConstraint(fields=('subscription', 'line', 'generation'), name='unique_identity_generation'),
        ),
        migrations.AddConstraint(
            model_name='usagestream',
            constraint=models.UniqueConstraint(fields=('identity', 'epoch'), name='unique_usage_epoch'),
        ),
        migrations.AddConstraint(
            model_name='usageledger',
            constraint=models.UniqueConstraint(fields=('stream', 'sequence'), name='unique_usage_sample'),
        ),
    ]
