# Generated by Django 5.2.17 on 2026-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_phase1_resources_and_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='metering_gap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
