# Generated by Django 5.2.17 on 2026-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_phase1_suspension_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='enforcement_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
