# Generated by Django 5.2.17 on 2026-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_line_multiple_ingresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='deployment_fence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='deployment_lease_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='deployment_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
