# Generated by Django 5.2.17 on 2026-09-30 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def initialize_service_ids(apps, schema_editor):
    """逐行生成服务标识；旧账期保持此前的零点规则，不重算历史。"""
    Entitlement = apps.get_model('portal', 'Entitlement')
    for record in Entitlement.objects.using(schema_editor.connection.alias).all().iterator():
        record.public_id = uuid.uuid4()
        record.reset_hour = 0
        record.reset_minute = 0
        record.save(using=schema_editor.connection.alias, update_fields=['public_id', 'reset_hour', 'reset_minute'])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_phase1_server_publication_fence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='raw_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='weighted_remainder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='reset_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='reset_minute',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(initialize_service_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='entitlement', name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='usageledger',
            name='quality',
            field=models.CharField(default='legacy_unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='usageledger',
            name='weighted_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='reset_day',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='CapacityPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('capacity_mode', models.CharField(choices=[('unknown', '未知'), ('limited', '有限容量'), ('unlimited', '不限量')], default='unknown', max_length=12)),
                ('planned_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('original_unit', models.CharField(default='GB', max_length=20)),
                ('accounting_basis', models.CharField(blank=True, max_length=120)),
                ('source_priority', models.JSONField(default=list)),
                ('stale_after_seconds', models.PositiveIntegerField(default=21600)),
                ('safety_bytes', models.PositiveBigIntegerField(default=0)),
                ('warning_percent', models.PositiveSmallIntegerField(default=70)),
                ('critical_percent', models.PositiveSmallIntegerField(default=85)),
                ('urgent_percent', models.PositiveSmallIntegerField(default=95)),
                ('overage_policy', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.server')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('severity', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='portal.capacitypool')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_bytes', models.PositiveBigIntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('reason', models.CharField(max_length=240)),
                ('request_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='portal.capacitypool')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', '供应商API'), ('agent', '探针观测'), ('manual', '人工校准')], max_length=12)),
                ('source_key', models.CharField(max_length=120)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('observed_at', models.DateTimeField()),
                ('used_bytes', models.PositiveBigIntegerField()),
                ('reported_capacity_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('quality', models.CharField(max_length=24)),
                ('accounting_basis', models.CharField(max_length=120)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='portal.capacitypool')),
            ],
        ),
        migrations.CreateModel(
            name='LineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('topology_verified', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_links', to='portal.line')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_links', to='portal.capacitypool')),
            ],
        ),
        migrations.CreateModel(
            name='LineRateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=12)),
                ('effective_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_versions', to='portal.line')),
            ],
            options={
                'ordering': ['effective_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='usageledger',
            name='rate_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.linerateversion'),
        ),
        migrations.AddConstraint(
            model_name='capacitypool',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='positive_capacity_period'),
        ),
        migrations.AddConstraint(
            model_name='capacityalert',
            constraint=models.UniqueConstraint(fields=('pool', 'code'), name='unique_capacity_alert'),
        ),
        migrations.AddConstraint(
            model_name='capacityadjustment',
            constraint=models.UniqueConstraint(fields=('pool', 'request_key'), name='unique_capacity_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='capacitysample',
            constraint=models.UniqueConstraint(fields=('pool', 'source', 'source_key'), name='unique_capacity_sample'),
        ),
        migrations.AddConstraint(
            model_name='linecapacity',
            constraint=models.UniqueConstraint(fields=('line', 'pool'), name='unique_line_capacity'),
        ),
        migrations.AddConstraint(
            model_name='linecapacity',
            constraint=models.CheckConstraint(condition=models.Q(('consumption_factor__gt', 0)), name='positive_capacity_factor'),
        ),
        migrations.AddConstraint(
            model_name='linerateversion',
            constraint=models.UniqueConstraint(fields=('line', 'effective_at'), name='unique_line_rate_time'),
        ),
        migrations.AddConstraint(
            model_name='linerateversion',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gt', 0)), name='positive_line_rate'),
        ),
    ]
