# Generated by Django 5.2.17 on 2026-09-30 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_service_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeliveryReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('subscription_ids', models.JSONField(default=list)),
                ('job_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='devicesubscription',
            name='delivery_scope',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='devicesubscription',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('delivery_scope', ''), _negated=True), models.Q(('state__in', ['disabled', 'disabling']), _negated=True)), fields=('entitlement', 'client', 'delivery_scope'), name='unique_active_service_delivery'),
        ),
        migrations.AddField(
            model_name='servicedeliveryreset',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicedeliveryreset',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_resets', to='portal.entitlement'),
        ),
        migrations.AddConstraint(
            model_name='servicedeliveryreset',
            constraint=models.UniqueConstraint(fields=('entitlement', 'key'), name='unique_service_reset_request'),
        ),
    ]
