# Generated by Django 5.2.17 on 2026-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_service_delivery_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nodeidentity',
            name='unique_identity_generation',
        ),
        migrations.AddConstraint(
            model_name='nodeidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('subscription', 'line', 'ingress', 'generation'), name='unique_identity_generation'),
        ),
    ]
